language: python
cache:
  - pip
  - directories:
      - "$HOME/.pyenv"
      - "$HOME/Library/Caches/Homebrew"
notifications:
  email: false
sudo: required
dist: xenial
services:
  - docker
python:
  - 3.6
  - 3.7
  - 3.8
addons:
  apt:
    packages:
      - openssh-server
      - rpm
      - dpkg
      - cmake
install:
  - pip install flake8 jinja2 sphinx sphinx_rtd_theme
  - python setup.py build_ext --inplace
  - eval "$(ssh-agent -s)"
script:
  - pytest tests
  - flake8 ssh2
  # Test source distribution builds
  - python setup.py sdist
  - cd dist
  - pip install *
  - python -c 'from ssh2.session import Session; Session()'
  - cd ..
  - cd doc
  - make html
  - cd ..

jobs:
  include:

    - &osx-wheels
      stage: build packages
      os: osx
      osx_image: xcode9.2
      env:
        - SYSTEM_LIBSSH2: 1
      before_cache:
        - brew cleanup
      before_install:
        - brew update
        - brew install ccache
        - brew outdated openssl || travis_wait brew upgrade openssl || echo "y"
        - brew link --overwrite python@2 || brew install python@2 || brew link --overwrite python@2
        - which python2
        - python3 -c "import ssl; from platform import python_version; print(ssl.OPENSSL_VERSION); print(python_version())"
        - sudo -H pip3 install twine
        - which twine
        - sudo ci/install-ssh2.sh
        - cp /usr/local/lib/libssh2* .
        - mkdir -p wheels
      install:
        - sudo -H pip2 install -U delocate wheel pip setuptools
        - ls -lh
      script:
        - pip2 wheel .
        - delocate-listdeps --all *.whl
        - delocate-wheel -v *.whl
        - delocate-listdeps --all *.whl
        - ls -l *.whl
        - rm -f *.dylib
        - pip2 install --user -v *.whl
        - pwd; mkdir temp; cd temp; pwd
        - python -c "from ssh2.session import Session; Session()"
        - cd ..; pwd
        - mv -f *.whl wheels/
      after_success:
        - if [[ ! -z "$TRAVIS_TAG" ]]; then
              twine upload --skip-existing -u $PYPI_U -p $PYPI_P wheels/*.whl;
          fi
      language: generic
      python: skip

    - <<: *osx-wheels
      osx_image: xcode9.2

    - <<: *osx-wheels
      osx_image: xcode9.2
      env:
        - PYENV: 3.6.4
        - SYSTEM_LIBSSH2: 1
      install: skip
      script:
        - travis_wait ./ci/travis/pyenv-wheel.sh

    - <<: *osx-wheels
      osx_image: xcode9.4
      env:
        - PYENV: 3.6.4
        - SYSTEM_LIBSSH2: 1
      install: skip
      script:
        - travis_wait ./ci/travis/pyenv-wheel.sh

    - <<: *osx-wheels
      osx_image: xcode9.2
      env:
        - PYENV: 3.7.0
        - SYSTEM_LIBSSH2: 1
      install: skip
      script:
        - travis_wait ./ci/travis/pyenv-wheel.sh

    - <<: *osx-wheels
      osx_image: xcode9.4
      env:
        - PYENV: 3.7.0
        - SYSTEM_LIBSSH2: 1
      install: skip
      script:
        - travis_wait ./ci/travis/pyenv-wheel.sh

    - stage: build packages
      os: linux
      python: 3.6
      env:
        - WHEELS=1
      install:
        - pip install twine
      script:
        - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi
        - ./ci/travis/build-manylinux.sh
      after_success:
        - if [[ ! -z "$TRAVIS_TAG" ]]; then
              twine upload --skip-existing -u $PYPI_U -p $PYPI_P wheelhouse/*.whl;
          fi
      deploy:
        - provider: pypi
          skip_cleanup: true
          on:
            repo: pycopia/ssh2-python3
            tags: true
          distributions: sdist
          user: XXX
          password:
            secure: ""
